# Auto-generated
CREWS={
    "MONKEY. D. LUFFY": "🏴 Straw Hat Pirates",
    "RORONOA ZORO": "🏴 Straw Hat Pirates",
    "NAMI": "🏴 Straw Hat Pirates",
    "USOPP": "🏴 Straw Hat Pirates",
    "SANJI": "🏴 Straw Hat Pirates",
    "TONY TONY. CHOPPER": "🏴 Straw Hat Pirates",
    "NICO ROBIN": "🏴 Straw Hat Pirates",
    "FRANKY": "🏴 Straw Hat Pirates",
    "BROOK": "🏴 Straw Hat Pirates",
    "JINBE": "🏴 Straw Hat Pirates",
    "GOING MERRY": "🌍 Other",
    "THOUSAND SUNNY": "🌍 Other",
    "GOL D.  ROGER (GOLD ROGER)": "🌍 Other",
    "SHANKS": "🟥 Red Hair Pirates",
    "LUCKY. ROO": "🌍 Other",
    "YASOPP": "🌍 Other",
    "BENN. BECKMAN": "🌍 Other",
    "ANJO": "🌍 Other",
    "MONSTER": "🌍 Other",
    "MIKIO ITOO": "🌍 Other",
    "MAKINO": "🌍 Other",
    "HIGUMA": "🌍 Other",
    "GYOLL": "🌍 Other",
    "Mrs.  CHICKEN": "🌍 Other",
    "WOOP SLAP": "🌍 Other",
    "LOCAL SEA MONSTER": "🌍 Other",
    "KOBY": "⚓ Marines",
    "ALVIDA": "🌍 Other",
    "HEPPOKO PEPPOKO & POPPOKO": "🌍 Other",
    "RIKA": "🌍 Other",
    "RIRIKA": "🌍 Other",
    "SOLO": "🌍 Other",
    "MORGAN": "🌍 Other",
    "HELMEPPO": "⚓ Marines",
    "ROKKAKU": "🌍 Other",
    "CARELESSO": "🌍 Other",
    "KUINA": "🌍 Other",
    "KOUSHIROU": "🌍 Other",
    "RIPPER": "🌍 Other",
    "PINKY THE BIRD": "🌍 Other",
    "TIGHTROPE FUNAN BOROS": "🌍 Other",
    "ALMIGHTY DOMINGOS": "🌍 Other",
    "BUGGY": "🌍 Other",
    "MOHJI": "🌍 Other",
    "RICHIE": "🌍 Other",
    "CABAJI": "🌍 Other",
    "DOMO-KUN": "🌍 Other",
    "NIMBLE FUWARS": "🌍 Other",
    "SHUSHU": "🌍 Other",
    "BOODLE": "🌍 Other",
    "HOCKER": "🌍 Other",
    "PORO": "🌍 Other",
    "BUCKOX": "🌍 Other",
    "GAIMON": "🌍 Other",
    "MORNIN": "🌍 Other",
    "CARROT": "🌍 Other",
    "PEPPER": "🌍 Other",
    "ONION": "🌍 Other",
    "KURO(KLAHADORE)": "🌍 Other",
    "JANGO": "🌍 Other",
    "SHAM": "🌍 Other",
    "BUCHI": "🌍 Other",
    "KAYA": "🌍 Other",
    "MERRY": "🌍 Other",
    "SNOTT MEE": "🌍 Other",
    "BANKINA": "🌍 Other",
    "YOSAKU": "🌍 Other",
    "JOHNNY": "🌍 Other",
    "FULLBODY": "🌍 Other",
    "MOODY": "🌍 Other",
    "Mr.  MOTZEL": "🌍 Other",
    "ZEFF": "🌍 Other",
    "BACCHY": "🌍 Other",
    "PATTY": "🌍 Other",
    "LINES": "🌍 Other",
    "PANDAMAN": "🌍 Other",
    "GIN": "🌍 Other",
    "CARNE": "🌍 Other",
    "ROXANNE": "🌍 Other",
    "KRIEG": "🌍 Other",
    "DRACULE. MIHAWK": "🌍 Other",
    "PEARL": "🌍 Other",
    "IDEAMAN": "🌍 Other",
    "HUSTLE": "🌍 Other",
    "KEYGAN": "🌍 Other",
    "PANSHARK": "🌍 Other",
    "FISH-WOMAN NAMI": "🏴 Straw Hat Pirates",
    "NEZUMI": "🌍 Other",
    "ARLONG": "🌍 Other",
    "HATCHAN": "🌍 Other",
    "MOMOO": "🌍 Other",
    "CHEW": "🌍 Other",
    "KUROOBI": "🌍 Other",
    "CHABO": "🌍 Other",
    "NOJIKO": "🌍 Other",
    "GENZO": "🌍 Other",
    "KANESHIRO": "🌍 Other",
    "PISARO": "🌍 Other",
    "SALTGRILL": "🌍 Other",
    "TAKE": "🌍 Other",
    "PURINPURIN": "🌍 Other",
    "BELLEMERE": "🌍 Other",
    "Dr.  NAKO": "🌍 Other",
    "MAMEEMEE": "🌍 Other",
    "SAM": "🌍 Other",
    "TRANSPONDER SNAIL": "🌍 Other",
    "NEWS COO": "🌍 Other",
    "BRANNEW": "🌍 Other",
    "JOHN GIANT": "🌍 Other",
    "PACKY": "🌍 Other",
    "KOZE": "🌍 Other",
    "HANGER": "🌍 Other",
    "IPPONMATSU": "🌍 Other",
    "IPPON UME": "🌍 Other",
    "SAPEE": "🌍 Other",
    "MASHIKAKU": "🌍 Other",
    "SMOKER": "⚓ Marines",
    "TASHIGI": "⚓ Marines",
    "YU": "🌍 Other",
    "MONKEY. D. DRAGON": "🏴 Straw Hat Pirates",
    "KUMATE TRIBE": "🌍 Other",
    "NEFELTARI VIVI(Miss WEDNESDAY)": "🌍 Other",
    "KAROO": "🌍 Other",
    "CROCODILE(Mr. 0)": "🌍 Other",
    "DAZ BONEZ(Mr. 1)": "🌍 Other",
    "ZALA(Miss. DOUBLEFINGER)": "🌍 Other",
    "BENTHAM(Mr. 2/BON・KUREI)": "🌍 Other",
    "GALDINO(Mr. 3)": "🌍 Other",
    "MARIANNE(Miss. GOLDENWEEK)": "🌍 Other",
    "BABE(Mr. 4)": "🌍 Other",
    "DROPHY(Miss. MERRYCHRISTMAS)": "🌍 Other",
    "LASSOO ": "🌍 Other",
    "GEM(Mr. 5)": "🌍 Other",
    "MIKITA(Miss. VALENTINE)": "🌍 Other",
    "CROCUS": "🌍 Other",
    "LABOON": "🌍 Other",
    "Mr.  9": "🌍 Other",
    "Mr.  13": "🌍 Other",
    "Miss FRIDAY": "🌍 Other",
    "Mr.  SNOWMAN": "🌍 Other",
    "SNOW QUEEN": "🌍 Other",
    "IGARAM (Mr.  8 / IGARAPPOI)": "🌍 Other",
    "Miss MONDAY": "🌍 Other",
    "Mr.  BEANS": "🌍 Other",
    "Miss KATHERINA": "🌍 Other",
    "Mr.  SHIMIZU": "🌍 Other",
    "HENOHENOUNCHI": "🌍 Other",
    "BRONTOSAURUS": "🌍 Other",
    "BROGY": "🌍 Other",
    "DORRY": "🌍 Other",
    "SAMURAI BATTS": "🌍 Other",
    "BANANA GATOR": "🌍 Other",
    "Mr.  11": "🌍 Other",
    "ISLAND EATER": "🌍 Other",
    "YUKI": "🌍 Other",
    "AKUMAI": "🌍 Other",
    "WAPOL": "🌍 Other",
    "CHESS": "🌍 Other",
    "KUROMARIMO": "🌍 Other",
    "HIKING BEAR": "🌍 Other",
    "MARIA ONION BEAR": "🌍 Other",
    "DALTON": "🌍 Other",
    "SUPER SNOWMAN": "🌍 Other",
    "SHIRORA": "🌍 Other",
    "LAPINS": "🌍 Other",
    "TAMACHIBI": "🌍 Other",
    "Dr. KUREHA": "🌍 Other",
    "ROBSON": "🌍 Other",
    "20 DOCTORS・100 DOCTORS": "🌍 Other",
    "SNOWBIRD": "🌍 Other",
    "Dr. HIRILUK": "🌍 Other",
    "THALASSA LUCAS": "🌍 Other",
    "NEFELTARI COBRA": "🌍 Other",
    "PUPPU": "🌍 Other",
    "SEA CAT": "🌍 Other",
    "YOSHIMOTO": "🌍 Other",
    "PORTGAS. D. ACE": "🌍 Other",
    "Mr.  MELOW": "🌍 Other",
    "BUNCH": "🌍 Other",
    "LIZARD RUNNERS": "🌍 Other",
    "KUNG-FU DUGONG": "🌍 Other",
    "EVIL HERON": "🌍 Other",
    "SANDORA LIZARD": "🌍 Other",
    "MATSUGE": "🌍 Other",
    "TOTO": "🌍 Other",
    "KOZA": "🌍 Other",
    "OKAME": "🌍 Other",
    "NATTO": "🌍 Other",
    "KEBI": "🌍 Other",
    "MOTHER ASWA": "🌍 Other",
    "AGOTOGI": "🌍 Other",
    "KAPPA": "🌍 Other",
    "FALAFRA": "🌍 Other",
    "ERIC": "🌍 Other",
    "PELL": "🌍 Other",
    "CHAKA": "🌍 Other",
    "ULTRA KING": "🌍 Other",
    "KOALA GANG": "🌍 Other",
    "PINCERS": "🌍 Other",
    "ACCELLEGATOR": "🌍 Other",
    "SANDORA CATFISH": "🌍 Other",
    "STOMP": "🌍 Other",
    "IVAN X": "🌍 Other",
    "COWBOY": "🌍 Other",
    "BOURBON Jr. ": "🌍 Other",
    "CENTAUR": "🌍 Other",
    "HIKOICHI": "🌍 Other",
    "ARROW": "🌍 Other",
    "HYOTA": "🌍 Other",
    "BARREL": "🌍 Other",
    "BRAHM": "🌍 Other",
    "Mr.  7": "🌍 Other",
    "Miss FATHER'S DAY": "🌍 Other",
    "Mr.  LOVE": "🌍 Other",
    "HINA": "⚓ Marines",
    "Dr.  OOH": "🌍 Other",
    "TERRACOTTA": "🌍 Other",
    "SHINE": "🌍 Other",
    "MAIDY": "🌍 Other",
    "NEFELTARI TITI": "🌍 Other",
    "MAKKO": "🌍 Other",
    "Dr.  POTSUN": "🌍 Other",
    "EUREKA": "🌍 Other",
    "OCTOPAKO": "🌍 Other",
    "MASH": "🌍 Other",
    "GOLDFISH PRINCESS": "🌍 Other",
    "SEA BOAR": "🌍 Other",
    "BELLAMY": "🌍 Other",
    "SARQUISS": "🌍 Other",
    "LILY": "🌍 Other",
    "RIVERS": "🌍 Other",
    "ROSS": "🌍 Other",
    "EDDY": "🌍 Other",
    "HEWITT": "🌍 Other",
    "MANI": "🌍 Other",
    "MJURE": "🌍 Other",
    "ROSHIO": "🌍 Other",
    "SPECTOR": "🌍 Other",
    "TERRY": "🌍 Other",
    "RYCE": "🌍 Other",
    "MONT BLANC CRICKET": "🌍 Other",
    "MASIRA": "🌍 Other",
    "SHOUJOU": "🌍 Other",
    "UTAN DIVERS": "🌍 Other",
    "SOUTH BIRD": "🌍 Other",
    "JOBO": "🌍 Other",
    "FIVE ELDER A": "🌍 Other",
    "FIVE ELDER B": "🌍 Other",
    "FIVE ELDER C": "🌍 Other",
    "FIVE ELDER D": "🌍 Other",
    "FIVE ELDER E": "🌍 Other",
    "SENGOKU": "⚓ Marines",
    "TSURU": "⚓ Marines",
    "STAINLESS": "🌍 Other",
    "CANCER": "🌍 Other",
    "MOZAMBIA": "🌍 Other",
    "DONQUIXOTE DOFLAMINGO": "🌍 Other",
    "BARTHOLOMEW. KUMA": "🌍 Other",
    "ROCKSTAR": "🌍 Other",
    "EDWARD NEWGATE (WHITEBEARD)": "🌍 Other",
    "MARSHALL D.  TEACH (BLACKBEARD)": "🌍 Other",
    "LAFFITTE": "🌍 Other",
    "JESUS. BURGESS": "🌍 Other",
    "VAN. AUGUR": "🌍 Other",
    "DOC. Q": "🌍 Other",
    "STRONGER": "🌍 Other",
    "SKY FISH": "🌍 Other",
    "GAN. FALL": "🌍 Other",
    "PIERRE": "🌍 Other",
    "AMAZON": "🌍 Other",
    "EXPRESS LOBSTER": "🌍 Other",
    "CONIS": "🌍 Other",
    "SU": "🌍 Other",
    "PAGAYA": "🌍 Other",
    "McKINLEY": "🌍 Other",
    "ENEL": "🌍 Other",
    "SATORI": "🌍 Other",
    "SHURA": "🌍 Other",
    "FUZA": "🌍 Other",
    "OHM": "🌍 Other",
    "HOLY": "🌍 Other",
    "GEDATSU": "🌍 Other",
    "YAMA": "🌍 Other",
    "WYPER": "🌍 Other",
    "KAMAKIRI": "🌍 Other",
    "BRAHAM": "🌍 Other",
    "GENBO": "🌍 Other",
    "RAKI": "🌍 Other",
    "AISA": "🌍 Other",
    "KLABAUTERMANN": "🌍 Other",
    "KASHIGAMI": "🌍 Other",
    "NOLA": "🌍 Other",
    "ISA": "🌍 Other",
    "GODE THE WISE": "🌍 Other",
    "HOTORI": "🌍 Other",
    "KOTORI": "🌍 Other",
    "YOTSUBANE": "🌍 Other",
    "MAYUSHKA": "🌍 Other",
    "WARASHI": "🌍 Other",
    "MOYLE": "🌍 Other",
    "MOCHI": "🌍 Other",
    "CHIEF": "🌍 Other",
    "KALGARA": "🌍 Other",
    "MONT BLANC NOLAND": "🌍 Other",
    "PANTORI": "🌍 Other",
    "SETO": "🌍 Other",
    "MUSSE": "🌍 Other",
    "HERB": "🌍 Other",
    "MARILYN": "🌍 Other",
    "OCTOBALLOON": "🌍 Other",
    "BOXER": "🌍 Other",
    "KINDERELLA": "🌍 Other",
    "Dr.  BLACKBEARD": "🌍 Other",
    "MODA": "🌍 Other",
    "COMILLE": "🌍 Other",
    "KYUJI": "🌍 Other",
    "KODA": "🌍 Other",
    "SEA MONKEY": "🏴 Straw Hat Pirates",
    "RAINBOW MORAY BROTHERS": "🌍 Other",
    "TONJIT": "🌍 Other",
    "SHERRY": "🌍 Other",
    "DAAACHSHUND": "🌍 Other",
    "PLAAATYPUS": "🌍 Other",
    "SNOOOW LEOPAAARD": "🌍 Other",
    "FOXY": "🌍 Other",
    "PORCHE": "🌍 Other",
    "HAMBURG": "🌍 Other",
    "KIBAGAERU": "🌍 Other",
    "ITOMIMIZU": "🌍 Other",
    "CHUCHUN": "🌍 Other",
    "CAPOTE": "🌍 Other",
    "MONDA": "🌍 Other",
    "PICKLES": "🌍 Other",
    "BIG BUN": "🌍 Other",
    "MOUNTAIN RICKY": "🌍 Other",
    "GEORGE MACH": "🌍 Other",
    "SONIE": "🌍 Other",
    "DONOVAN": "🌍 Other",
    "GINA": "🌍 Other",
    "KUZAN (AOKIJI)": "🌍 Other",
    "CHIMNEY": "🌍 Other",
    "GONBE": "🌍 Other",
    "KOKORO": "🌍 Other",
    "MIKAZUKI": "🌍 Other",
    "YAGARA BULL": "🌍 Other",
    "ZAMBAI": "🌍 Other",
    "SCHOLLZO": "🌍 Other",
    "KOPP": "🌍 Other",
    "TAMAGON": "🌍 Other",
    "KIEV": "🌍 Other",
    "VERREE FINEWORK": "🌍 Other",
    "ICEBURG": "🌍 Other",
    "TYRANNOSAURUS": "🌍 Other",
    "PEEPLEY LULU": "🌍 Other",
    "TILESTONE": "🌍 Other",
    "PAULIE": "🌍 Other",
    "ROB LUCCI": "🌍 Other",
    "HATTORI": "🌍 Other",
    "KAKU": "🌍 Other",
    "KALIFA": "🌍 Other",
    "BLUENO": "🌍 Other",
    "JABRA": "🌍 Other",
    "KUMADORI": "🌍 Other",
    "FUKUROU": "🌍 Other",
    "NERO": "🌍 Other",
    "CORGY": "🌍 Other",
    "BLOCKHEAD": "🌍 Other",
    "Dr.  FIRSTAID": "🌍 Other",
    "KIWI": "🌍 Other",
    "MOZU": "🌍 Other",
    "HAPPA YAMAO": "🌍 Other",
    "TOM": "🌍 Other",
    "YOKOZUNA": "🌍 Other",
    "JUDGE GEORGE": "🌍 Other",
    "SPANDAM": "🌍 Other",
    "BUSHON": "🌍 Other",
    "STAYBE": "🌍 Other",
    "JERRY": "🌍 Other",
    "SODOMU": "🌍 Other",
    "GOMORA": "🌍 Other",
    "T BONE": "🌍 Other",
    "WANZE": "🌍 Other",
    "MICHAEL": "🌍 Other",
    "HOICHAEL": "🌍 Other",
    "HERCULEAN DESTROYERS": "🌍 Other",
    "KASHII": "🌍 Other",
    "OIMO": "🌍 Other",
    "GATHERINE": "🌍 Other",
    "BASKERVILLE": "🌍 Other",
    "COURTHOUSE GUARD DOG UNIT": "🌍 Other",
    "11 RIGHTEOUS JURORS": "🌍 Other",
    "AUNT ROJI": "🌍 Other",
    "MIZUIRA": "🌍 Other",
    "ORAN": "🌍 Other",
    "BUSSHIRI": "🌍 Other",
    "ROSHU": "🌍 Other",
    "HUCK": "🌍 Other",
    "LINT": "🌍 Other",
    "GRAM": "🌍 Other",
    "ZAYDE": "🌍 Other",
    "HOCHA": "🌍 Other",
    "CLOVER": "🌍 Other",
    "JAGUAR. D. SAUL": "🌍 Other",
    "SPANDINE": "🌍 Other",
    "LASKY": "🌍 Other",
    "NICO OLVIA": "🌍 Other",
    "MONEYPENNY": "🌍 Other",
    "ABSCONDO": "🌍 Other",
    "CHESSKIPPER": "🌍 Other",
    "FUNKFREED": "🌍 Other",
    "CHICKEN": "🌍 Other",
    "MOMONGA": "🌍 Other",
    "ONIGUMO": "🌍 Other",
    "DOBERMAN": "🌍 Other",
    "YAMAKAJI": "🌍 Other",
    "STRAWBERRY": "🌍 Other",
    "BERRY GOOD": "🌍 Other",
    "SHU": "🌍 Other",
    "SHARINGLE": "🌍 Other",
    "MONKEY. D. GARP": "🏴 Straw Hat Pirates",
    "MARCO": "🌍 Other",
    "JOZU": "🌍 Other",
    "ATTACH": "🌍 Other",
    "MARMIETA": "🌍 Other",
    "YAMENAHARE": "🌍 Other",
    "THATCH": "🌍 Other",
    "TERRY GILTEO": "🌍 Other",
    "GORO": "🌍 Other",
    "EARTH BOSS": "🌍 Other",
    "FOREST BOSS": "🌍 Other",
    "SPACEY": "🌍 Other",
    "SERGEANT COSMO": "🌍 Other",
    "GENERAL GALAXY": "🌍 Other",
    "CAPTAIN MACRO": "🌍 Other",
    "Dr.  TSUKIMI": "🌍 Other",
    "CAPTAIN SEAMARS": "🌍 Other",
    "GECKO MORIA": "🌍 Other",
    "ABSALOM": "🌍 Other",
    "PERONA": "🌍 Other",
    "HOGBACK": "🌍 Other",
    "VICTORIA CINDRY": "🌍 Other",
    "OARS": "🌍 Other",
    "CERBERUS": "🌍 Other",
    "HILDON": "🌍 Other",
    "McTREENALD": "🌍 Other",
    "UNIGARO": "🌍 Other",
    "OINKCHUCK": "🌍 Other",
    "RUG BEAR": "🌍 Other",
    "SPOIL": "🌍 Other",
    "KUMACY": "🌍 Other",
    "GYORO": "🌍 Other",
    "NIN": "🌍 Other",
    "BAO": "🌍 Other",
    "RYUMA": "🌍 Other",
    "CAPTAIN JOHN": "🌍 Other",
    "CHARLOTTE　LOLA": "🍰 Big Mom Pirates",
    "RISKY BROTHERS": "🌍 Other",
    "DOG PENGUIN": "❤️ Heart Pirates",
    "JIGORO": "🌍 Other",
    "TARALAN": "🌍 Other",
    "SPIDER MOUSE": "🌍 Other",
    "HIPPO GENTLEMAN": "🌍 Other",
    "CAPTAIN GOO": "🌍 Other",
    "HEERCOMES DASUN": "🌍 Other",
    "EHGANA": "🌍 Other",
    "MARGARITA": "🌍 Other",
    "YORKI": "🌍 Other",
    "MIZUUTA MADAISKY": "🌍 Other",
    "MIZUUTA MAWARITOSKY": "🌍 Other",
    "SEA RABBIT": "🌍 Other",
    "CAMIE": "🌍 Other",
    "PAPPAG": "🌍 Other",
    "DUVAL": "🌍 Other",
    "MACRO": "🌍 Other",
    "GYARO": "🌍 Other",
    "TANSUI": "🌍 Other",
    "MOTOBARO": "🌍 Other",
    "ANTONIO": "🌍 Other",
    "DEVIL DIAS": "🌍 Other",
    "SAINT ROSWARD": "🌍 Other",
    "SAINT CHARLOS": "🌍 Other",
    "SAINT SHALRIA": "🌍 Other",
    "SALOU": "🌍 Other",
    "JEAN BART": "❤️ Heart Pirates",
    "KAIRIKEN": "🌍 Other",
    "MINORUBA": "🌍 Other",
    "SHAKUYAKU": "🌍 Other",
    "CAPONE. BEGE": "🌍 Other",
    "JEWELRY. BONNEY": "🌍 Other",
    "BASIL. HAWKINS": "🌍 Other",
    "EUSTASS. KID": "🌍 Other",
    "SCRATCHMEN. APOO": "🌍 Other",
    "X. DRAKE": "🌍 Other",
    "UROUGE": "🌍 Other",
    "KILLER": "🌍 Other",
    "TRAFALGAR LAW (TRAFALGAR D.  WATER LAW)": "❤️ Heart Pirates",
    "BEPO": "❤️ Heart Pirates",
    "PENGUIN": "❤️ Heart Pirates",
    "SHACHI": "❤️ Heart Pirates",
    "PETERMAN": "🌍 Other",
    "MARIE": "🌍 Other",
    "JUDI": "🌍 Other",
    "MARIN": "🌍 Other",
    "HEAT": "🌍 Other",
    "WIRE": "🌍 Other",
    "DISCO": "🌍 Other",
    "STANSEN": "🌍 Other",
    "SILVERS. RAYLEIGH": "🌍 Other",
    "PASIA": "🌍 Other",
    "BYRON": "🌍 Other",
    "COFFEE MONKEYS": "🏴 Straw Hat Pirates",
    "LACUBA": "🌍 Other",
    "SICILY": "🌍 Other",
    "PACIFISTA": "🌍 Other",
    "BORSALINO (KIZARU)": "🌍 Other",
    "FAUST": "🌍 Other",
    "SENTOMARU": "🌍 Other",
    "BOA. HANCOCK": "🌍 Other",
    "BOA. SANDERSONIA": "🌍 Other",
    "BOA. MARIGOLD": "🌍 Other",
    "SALOME": "🌍 Other",
    "GLORIOSA (ELDER NYON)": "🌍 Other",
    "MARGUERITE": "🌍 Other",
    "SWEET PEA": "🌍 Other",
    "APHELANDRA": "🌍 Other",
    "BELLADONNA": "🌍 Other",
    "KIKYO": "🌍 Other",
    "NERINE": "🌍 Other",
    "POPPY": "🌍 Other",
    "PANSY": "🌍 Other",
    "GENISTA": "🌍 Other",
    "PANDAWOMANMI": "🌍 Other",
    "YUDA": "🌍 Other",
    "RAN": "🌍 Other",
    "COSMOS": "🌍 Other",
    "RINDO": "🌍 Other",
    "BLUEFAN": "🌍 Other",
    "DAISY": "🌍 Other",
    "BACURA": "🌍 Other",
    "HAREDAS": "🌍 Other",
    "TAROIMO": "🌍 Other",
    "TIBBANY": "🌍 Other",
    "HERACLES": "🌍 Other",
    "SAYIN GOABIRDS": "🌍 Other",
    "SHAMBA": "🌍 Other",
    "STALKER": "🌍 Other",
    "MAGELLAN": "🌍 Other",
    "HANNYABAL": "🌍 Other",
    "DOMINO": "🌍 Other",
    "SALDEATH": "🌍 Other",
    "LITTLE SADI": "🌍 Other",
    "BLUE GORILLAS (BLUGORI)": "🌍 Other",
    "BASILISK": "🌍 Other",
    "PUZZLE SCORPIONS": "🌍 Other",
    "MANTICORE": "🌍 Other",
    "SPHYNX": "🌍 Other",
    "MINOTAURUS": "🌍 Other",
    "MINORHINOCEROS": "🌍 Other",
    "MINOKOALA": "🌍 Other",
    "MINOZEBRA": "🌍 Other",
    "ARMY WOLVES": "🌍 Other",
    "LOKI CLOWNIN": "🌍 Other",
    "NOTTA MAGICIAN": "🌍 Other",
    "DAIGIN": "🌍 Other",
    "BURR": "🌍 Other",
    "JUSTY TINBREAD": "🌍 Other",
    "DEZ TINNY": "🌍 Other",
    "RATHERBY SEIFER": "🌍 Other",
    "SPARA HEETPACK": "🌍 Other",
    "MUSHROOM": "🌍 Other",
    "DOBBY IBADONBO": "🌍 Other",
    "HOWJA GEDDINTHERE II": "🌍 Other",
    "EMPORIO. IVANKOV": "🌍 Other",
    "INAZUMA": "🌍 Other",
    "FRANCOIS": "🌍 Other",
    "ANTLERKOV": "🌍 Other",
    "BUNKOV": "🌍 Other",
    "PRINCE BERET": "🌍 Other",
    "SHILIEW": "🌍 Other",
    "UWESHALL NOTPASS": "🌍 Other",
    "REUDER": "🌍 Other",
    "PORTGAS D.  ROUGE": "🌍 Other",
    "SAKAZUKI (AKAINU)": "🌍 Other",
    "LONZ": "🌍 Other",
    "LACROIX": "🌍 Other",
    "DALMATION": "🌍 Other",
    "KANDRE": "🌍 Other",
    "VISTA": "🌍 Other",
    "BLAMENCO": "🌍 Other",
    "RAKUYO": "🌍 Other",
    "NAMULE": "🌍 Other",
    "BLENHEIM": "🌍 Other",
    "CURIEL": "🌍 Other",
    "KINGDEW": "🌍 Other",
    "HARUTA": "🌍 Other",
    "ATMOS": "🌍 Other",
    "SPEED JIL": "🌍 Other",
    "FOSSA": "🌍 Other",
    "IZO": "🌍 Other",
    "SQUARD": "🌍 Other",
    "LITTLEOARS JR. ": "🌍 Other",
    "DOMA": "🌍 Other",
    "MCGUY": "🌍 Other",
    "DECALVAN BROTHERS": "🌍 Other",
    "ELMY": "🌍 Other",
    "RAMBA": "🌍 Other",
    "A. O. ": "🌍 Other",
    "DELACUAJI": "🌍 Other",
    "EPOIDA": "🌍 Other",
    "WHITEY BAY": "🌍 Other",
    "NINTH": "🌍 Other",
    "BLONDIE": "🌍 Other",
    "AMADOB": "🌍 Other",
    "ANDRE": "🌍 Other",
    "ZODIA": "🌍 Other",
    "PALMS": "🌍 Other",
    "KARMA": "🌍 Other",
    "PAVLIK": "🌍 Other",
    "VITAN": "🌍 Other",
    "BIZARRE": "🌍 Other",
    "KECHATCH": "🌍 Other",
    "ISLEWAN": "🌍 Other",
    "HANGAN": "🌍 Other",
    "REFORTE": "🌍 Other",
    "WALLEM": "🌍 Other",
    "BAGGALY": "🌍 Other",
    "BREW": "🌍 Other",
    "BROCCA": "🌍 Other",
    "RUSH": "🌍 Other",
    "GREAT MICHAEL": "🌍 Other",
    "CANS": "🌍 Other",
    "CHOI": "🌍 Other",
    "KINGA": "🌍 Other",
    "COLSCON": "🌍 Other",
    "AGUSHILY": "🌍 Other",
    "JULIUS": "🌍 Other",
    "ZUKKA": "🌍 Other",
    "ARTHUR": "🌍 Other",
    "AVALO. PIZARRO": "🌍 Other",
    "CATARINA. DEVON": "🌍 Other",
    "SANJUAN. WOLF": "🌍 Other",
    "VASCO. SHOT": "🌍 Other",
    "BROWNDROS BEARDRIGUEZ (BROWNBEARD)": "🌍 Other",
    "CURLY. DADAN": "🌍 Other",
    "DOGURA": "🌍 Other",
    "MAGURA": "🌍 Other",
    "SABO": "🌍 Other",
    "PORCHEMY": "🌍 Other",
    "BLUEJAM": "🌍 Other",
    "OUTLOOK III": "🌍 Other",
    "DIDIT": "🌍 Other",
    "STERRY": "🌍 Other",
    "DUMAS REGAL IX": "🌍 Other",
    "DUMAS FAYES": "🌍 Other",
    "SAINT JALMACK": "🌍 Other",
    "SEA HIPPO": "🌍 Other",
    "THANKLIN": "🌍 Other",
    "HUMANDRILL": "🌍 Other",
    "BUNNY JOE": "🌍 Other",
    "CARRIER BAT": "🌍 Other",
    "KONG": "🌍 Other",
    "Dr.  FISHBONEN": "🌍 Other",
    "VICTIMOTHY CRUCIFIXIO": "🌍 Other",
    "KASA": "🌍 Other",
    "": "🌍 Other",
    " SCOTCH": "🌍 Other",
    "GORILLA": "🌍 Other",
    "HUMPHREY": "🌍 Other",
    "DEMALO BLACK (FAKE LUFFY)": "🌍 Other",
    "CHOCOLAT (FAKE NAMI)": "🏴 Straw Hat Pirates",
    "TURK (FAKE FRANKY)": "🏴 Straw Hat Pirates",
    "MOUNBLETEN (FAKE SOGE KING)": "🌍 Other",
    "MANJARO (FAKE ZORO)": "🌍 Other",
    "DRIP (FAKE SANJI)": "🏴 Straw Hat Pirates",
    "COCOA (FAKE ROBIN)": "🏴 Straw Hat Pirates",
    "STRAY FOX (FAKE CHOPPER)": "🏴 Straw Hat Pirates",
    "CARIBOU": "🌍 Other",
    "CORIBOU": "🌍 Other",
    "ALBION": "🌍 Other",
    "LIP ": "🌍 Other",
    " DOUGHTY": "🌍 Other",
    "CATACOMBO": "🌍 Other",
    "SURUME (KRAKEN)": "🌍 Other",
    "ANKORO": "🌍 Other",
    "NEPTUNE": "🌍 Other",
    "HOE": "🌍 Other",
    "FUKABOSHI": "🌍 Other",
    "RYUBOSHI": "🌍 Other",
    "MAMBOSHI": "🌍 Other",
    "SHIRAHOSHI": "🌍 Other",
    "MEGALO": "🌍 Other",
    "MINISTER OF THE RIGHT": "🌍 Other",
    "MINISTER OF THE LEFT": "🌍 Other",
    "HAMMOND": "🌍 Other",
    "KASAGOBA": "🌍 Other",
    "SEA LION": "🌍 Other",
    "ICHIKA": "🌍 Other",
    "NIKA": "🌍 Other",
    "SANKA": "🌍 Other",
    "YONKA": "🌍 Other",
    "YONKA TWO": "🌍 Other",
    "ISHILY": "🌍 Other",
    "MELLO": "🌍 Other",
    "SEIRA": "🌍 Other",
    "HIRAMELA": "🌍 Other",
    "KAIREN": "🌍 Other",
    "LULIS": "🌍 Other",
    "SOLA": "🌍 Other",
    "FIYONCE": "🌍 Other",
    "ADELLE": "🌍 Other",
    "AMMO KNIGHTS": "🌍 Other",
    "SPLASH": "🌍 Other",
    "SPLATTER": "🌍 Other",
    "SHIRLEY": "🌍 Other",
    "GYRO": "🌍 Other",
    "HODY JONES": "🌍 Other",
    "DOSUN": "🌍 Other",
    "ZEO": "🌍 Other",
    "DARUMA": "🌍 Other",
    "IKAROS MUCH": "🌍 Other",
    "HYOUZOU": "🌍 Other",
    "WADATSUMI": "🌍 Other",
    "VANDER DECKEN Ⅸ": "🌍 Other",
    "DEN": "🌍 Other",
    "FISHER TIGER": "🌍 Other",
    "OTOHIME": "🌍 Other",
    "KOALA": "🌍 Other",
    "ALADDIN": "🌍 Other",
    "JUNAN": "🌍 Other",
    "PAPANEEL": "🌍 Other",
    "KADAR": "🌍 Other",
    "DONQUIXOTE MJOSGARD": "🌍 Other",
    "SEA BEAR": "🌍 Other",
    "DAEDALUS": "🌍 Other",
    "HARISENBON": "🌍 Other",
    "MARIA NAPOLE": "🌍 Other",
    "PEKOMS": "🌍 Other",
    "BARON TAMAGO": "🌍 Other",
    "DRAGON NUMBER THIRTEEN": "🌍 Other",
    "SYND": "🌍 Other",
    "MOCHA": "🌍 Other",
    "KOMBU": "🌍 Other",
    "BEEYO": "🌍 Other",
    "ALLY": "🌍 Other",
    "DOLAN": "🌍 Other",
    "UZU": "🌍 Other",
    "MONET": "🌍 Other",
    "CAESAR. CLOWN": "🌍 Other",
    "ROCK": "🌍 Other",
    "SCOTCH": "🌍 Other",
    "REBAR SMOOTHY": "🌍 Other",
    "FEN BOCK THE GOURD": "🌍 Other",
    "ROPE-MASTER CHAPPE": "🌍 Other",
    "SMILEY": "🌍 Other",
    "VERGO": "🌍 Other",
    "KIN'EMON": "🌍 Other",
    "YARISUGI": "🌍 Other",
    "LUN THE MACHETE": "🌍 Other",
    "KOUZUKI MOMONOSUKE": "🌍 Other",
    "BABY FIVE": "🌍 Other",
    "BUFFALO": "🌍 Other",
    "CAMEL": "🌍 Other",
    "MAKINO'S BABY": "🌍 Other",
    "SARFUNKEL": "🌍 Other",
    "Mr.  9 & Miss MONDAY'S BABY": "🌍 Other",
    "NORTH BIRD": "🌍 Other",
    "WESTERN BIRD": "🌍 Other",
    "EASTERN BIRD": "🌍 Other",
    "GALLEY-LA'S GENIUS SECRETARY": "🌍 Other",
    "BIMINE": "🌍 Other",
    "MINOCHIHUAHUA": "🌍 Other",
    "GABURU'S GRANDMA": "🌍 Other",
    "GABURU": "🌍 Other",
    "MARIO": "🌍 Other",
    "ISSHO (FUJITORA)": "🌍 Other",
    "VIOLA (VIOLET)": "🌍 Other",
    "KYROS (ONE-LEGGED SOLDIER)": "🌍 Other",
    "GYATS": "🌍 Other",
    "SPARTAN": "🌍 Other",
    "CHINJAO": "🌍 Other",
    "SAI": "🌍 Other",
    "BOO": "🌍 Other",
    "KELLY FUNK": "🌍 Other",
    "BOBBY FUNK": "🌍 Other",
    "DAGAMA": "🌍 Other",
    "ELIZABELLO Ⅱ": "🌍 Other",
    "SULEIMAN": "🌍 Other",
    "ABDULLAH": "🌍 Other",
    "JEET": "🌍 Other",
    "ORLUMBUS": "🌍 Other",
    "CAVENDISH (HAKUBA)": "🌍 Other",
    "REBECCA": "🌍 Other",
    "GAMBIA": "🌍 Other",
    "MAYNARD": "🌍 Other",
    "BARTOLOMEO": "🌍 Other",
    "JEAN ANGO": "🌍 Other",
    "IDEO": "🌍 Other",
    "MOOCY": "🌍 Other",
    "HAJRUDIN": "🌍 Other",
    "MUMMY": "🌍 Other",
    "MEADOWS": "🌍 Other",
    "AGYO (FIGHTING LION)": "🌍 Other",
    "DAMASK": "🌍 Other",
    "ROLLING LOGAN": "🌍 Other",
    "ACILIA": "🌍 Other",
    "BLUEGILLY": "🌍 Other",
    "TANK LEPANTO": "🌍 Other",
    "RIKU DOLDO Ⅲ (RICKY)": "🌍 Other",
    "HACK": "🌍 Other",
    "FIGHTING FISH": "🌍 Other",
    "PEEKATHA KROTCH": "🌍 Other",
    "SAWYER WAYBACK": "🌍 Other",
    "GANCHO": "🌍 Other",
    "MANSHERRY": "🌍 Other",
    "LEO": "🌍 Other",
    "BOMBA": "🌍 Other",
    "RAMPO": "🌍 Other",
    "FLAPPER": "🌍 Other",
    "BOBOMBA": "🌍 Other",
    "NUBON": "🌍 Other",
    "PELLINI": "🌍 Other",
    "INHEL": "🌍 Other",
    "COTTON": "🌍 Other",
    "WICCA": "🌍 Other",
    "BAXCON": "🌍 Other",
    "DAIKON": "🌍 Other",
    "CUB": "🌍 Other",
    "BIAN": "🌍 Other",
    "GOLDEN RHINOCEROS BEETLES (YELLOW CUBS)": "🌍 Other",
    "PEACH-COLORED HORNETS": "🌍 Other",
    "HIGH-SPEED FOX": "🌍 Other",
    "GRABBA": "🌍 Other",
    "MOUJI": "🌍 Other",
    "BASTILLE": "🌍 Other",
    "ESTA": "🌍 Other",
    "MILO (ONEPOCO)": "🌍 Other",
    "FARUL": "🌍 Other",
    "DIAMANTE": "🌍 Other",
    "TREBOL": "🌍 Other",
    "PICA": "🌍 Other",
    "SUGAR": "🌍 Other",
    "GIOLLA": "🌍 Other",
    "LAO G": "🌍 Other",
    "SENOR. PINK": "🌍 Other",
    "MACHVISE": "🌍 Other",
    "DELLINGER": "🌍 Other",
    "GLADIUS": "🌍 Other",
    "KUWEEN": "🌍 Other",
    "Mr.  UNDERLING": "🌍 Other",
    "YVES": "🌍 Other",
    "SCARLETT": "🌍 Other",
    "KUROZUMI KANJURO": "🌍 Other",
    "SPRING SPARROW": "🌍 Other",
    "DONQUIXOTE　ROSINANTE(CORAZŌN)": "🌍 Other",
    "St.  DONQUIXOTE HOMING": "🌍 Other",
    "TRAFALGAR LAMMY": "🌍 Other",
    "WELLINGTON": "🌍 Other",
    "X.  BARRELS": "🌍 Other",
    "RUSSIAN": "🌍 Other",
    "GIMLET": "🌍 Other",
    "STAYA LIVE": "🌍 Other",
    "STELLA LIVE": "🌍 Other",
    "NEEDA HAND": "🌍 Other",
    "KAIDO": "🐉 Beasts Pirates",
    "OOK-OOK": "🌍 Other",
    "SEA KITTEN": "🌍 Other",
    "SEA DOG PATROLMAN": "🌍 Other",
    "CANDY SHOP GRANDMA": "🌍 Other",
    "EDWARD WEEVIL": "🌍 Other",
    "Miss BUCKIN": "🌍 Other",
    "ZUNESHA": "🌍 Other",
    "RYUNOSUKE": "🌍 Other",
    "WARNEY": "🌍 Other",
    "RODDY": "🌍 Other",
    "BB（BLACK BACK)": "🌍 Other",
    "WANDA": "🌍 Other",
    "CARROT": "🌍 Other",
    "NEKOZAEMON": "🌍 Other",
    "YOMO": "🌍 Other",
    "MIYAGI": "🌍 Other",
    "TRISTAN": "🌍 Other",
    "JACK": "🌍 Other",
    "SHEEPSHEAD": "🌍 Other",
    "GINRUMMY": "🌍 Other",
    "MON-JI": "🌍 Other",
    "SHISHILIAN": "🌍 Other",
    "GIOVANNI": "🌍 Other",
    "CONCELOT": "🌍 Other",
    "INUARASHI": "🌍 Other",
    "NEKOMAMUSHI": "🌍 Other",
    "CLIONE": "🌍 Other",
    "UNI": "🌍 Other",
    "IKKAKU": "🌍 Other",
    "VITO": "🌍 Other",
    "PEDRO": "🌍 Other",
    "MILKY": "🌍 Other",
    "TORASABURO": "🌍 Other",
    "BARIETE": "🌍 Other",
    "RAIZO": "🌍 Other",
    "SALLY ISNTOINETTE": "🌍 Other",
    "GOTTI": "🌍 Other",
    "ARMORED STONEFISH": "🌍 Other",
    "TERRITORIAL SEA SLUGS": "🌍 Other",
    "VINSMOKE JUDGE": "🌍 Other",
    "VINSMOKE REIJU": "🌍 Other",
    "VINSMOKE ICHJI": "🌍 Other",
    "VINSMOKE NIJI": "🌍 Other",
    "VINSMOKE YONJI": "🌍 Other",
    "VINSMOKE SORA": "🌍 Other",
    "CALICOACH": "🌍 Other",
    "PORKSWAGON": "🌍 Other",
    "CHARLOTTE LINLIN (BIG MOM)": "🍰 Big Mom Pirates",
    "CHARLOTTE PEROSPERAW": "🍰 Big Mom Pirates",
    "CHARLOTTE KATAKURI": "🍰 Big Mom Pirates",
    "CHARLOTTE DAIFUKU": "🍰 Big Mom Pirates",
    "CHARLOTTE OVEN": "🍰 Big Mom Pirates",
    "CHARLOTTE OPERA": "🍰 Big Mom Pirates",
    "CHARLOTTE COUNTER": "🍰 Big Mom Pirates",
    "CHARLOTTE CADENZA": "🍰 Big Mom Pirates",
    "CHARLOTTE CABALETTA": "🍰 Big Mom Pirates",
    "CHARLOTTE GALA": "🍰 Big Mom Pirates",
    "CHARLOTTE CRACKER": "🍰 Big Mom Pirates",
    "CHARLOTTE ZUCCOTTO": "🍰 Big Mom Pirates",
    "CHARLOTTE NUSSTORTE": "🍰 Big Mom Pirates",
    "CHARLOTTE BASSKARTE": "🍰 Big Mom Pirates",
    "CHARLOTTE DOSMARCHE": "🍰 Big Mom Pirates",
    "CHARLOTTE NOISETTE": "🍰 Big Mom Pirates",
    "CHARLOTTE MOSCATO": "🍰 Big Mom Pirates",
    "CHARLOTTE COMPO": "🍰 Big Mom Pirates",
    "CHARLOTTE LAURIN": "🍰 Big Mom Pirates",
    "CHARLOTTE MONT-D’OR": "🍰 Big Mom Pirates",
    "CHARLOTTE HIGH-FAT": "🍰 Big Mom Pirates",
    "CHARLOTTE TABLET": "🍰 Big Mom Pirates",
    "CHARLOTTE SAINT-MARC": "🍰 Big Mom Pirates",
    "CHARLOTTE BASANS": "🍰 Big Mom Pirates",
    "CHARLOTTE DACQUOISE": "🍰 Big Mom Pirates",
    "CHARLOTTE SNACK": "🍰 Big Mom Pirates",
    "CHARLOTTE BAVAROIS": "🍰 Big Mom Pirates",
    "CHARLOTTE KANTEN": "🍰 Big Mom Pirates",
    "CHARLOTTE KATO": "🍰 Big Mom Pirates",
    "CHARLOTTE MONTB": "🍰 Big Mom Pirates",
    "CHARLOTTE CHIBOUST": "🍰 Big Mom Pirates",
    "CHARLOTTE MOBILE": "🍰 Big Mom Pirates",
    "CHARLOTTE BROWNIE": "🍰 Big Mom Pirates",
    "CHARLOTTE RAISIN": "🍰 Big Mom Pirates",
    "CHARLOTTE MASCARPONE": "🍰 Big Mom Pirates",
    "CHARLOTTE YUEN": "🍰 Big Mom Pirates",
    "CHARLOTTE NEWICHI": "🍰 Big Mom Pirates",
    "CHARLOTTE NEWJI": "🍰 Big Mom Pirates",
    "CHARLOTTE NEWSAN": "🍰 Big Mom Pirates",
    "CHARLOTTE NEWSHI": "🍰 Big Mom Pirates",
    "CHARLOTTE NEWGO": "🍰 Big Mom Pirates",
    "CHARLOTTE NOUGAT": "🍰 Big Mom Pirates",
    "CHARLOTTE ANGLAISE": "🍰 Big Mom Pirates",
    "CHARLOTTE UIRO": "🍰 Big Mom Pirates",
    "CHARLOTTE DE-CHAT": "🍰 Big Mom Pirates",
    "CHARLOTTE DOLCE": "🍰 Big Mom Pirates",
    "CHARLOTTE DRAGEE": "🍰 Big Mom Pirates",
    "CHARLOTTE COMPOTE": "🍰 Big Mom Pirates",
    "CHARLOTTE MONDEE": "🍰 Big Mom Pirates",
    "CHARLOTTE AMANDE": "🍰 Big Mom Pirates",
    "CHARLOTTE HACHEE": "🍰 Big Mom Pirates",
    "CHARLOTTE EFFILEE": "🍰 Big Mom Pirates",
    "CHARLOTTE CUSTARD": "🍰 Big Mom Pirates",
    "CHARLOTTE ANGEL": "🍰 Big Mom Pirates",
    "CHARLOTTE BRULEE": "🍰 Big Mom Pirates",
    "CHARLOTTE BROYE": "🍰 Big Mom Pirates",
    "CHARLOTTE MASH": "🍰 Big Mom Pirates",
    "CHARLOTTE CORNSTARCH": "🍰 Big Mom Pirates",
    "CHARLOTTE MOZART": "🍰 Big Mom Pirates",
    "CHARLOTTE MARNIER": "🍰 Big Mom Pirates",
    "CHARLOTTE SMOOTHIE": "🍰 Big Mom Pirates",
    "CHARLOTTE CITRON": "🍰 Big Mom Pirates",
    "CHARLOTTE CINNAMON": "🍰 Big Mom Pirates",
    "CHARLOTTE MELISE": "🍰 Big Mom Pirates",
    "CHARLOTTE GALETTE": "🍰 Big Mom Pirates",
    "CHARLOTTE POIRE": "🍰 Big Mom Pirates",
    "CHARLOTTE PRIM": "🍰 Big Mom Pirates",
    "CHARLOTTE PRALINE": "🍰 Big Mom Pirates",
    "CHARLOTTE CHIFFON": "🍰 Big Mom Pirates",
    "CHARLOTTE MARBLE": "🍰 Big Mom Pirates",
    "CHARLOTTE MYUKURU": "🍰 Big Mom Pirates",
    "CHARLOTTE MAPLE": "🍰 Big Mom Pirates",
    "CHARLOTTE JOCONDE": "🍰 Big Mom Pirates",
    "CHARLOTTE PANNA": "🍰 Big Mom Pirates",
    "CHARLOTTE JOSCARPONE": "🍰 Big Mom Pirates",
    "CHARLOTTE NUTMEG": "🍰 Big Mom Pirates",
    "CHARLOTTE AKIMEG": "🍰 Big Mom Pirates",
    "CHARLOTTE ALLMEG": "🍰 Big Mom Pirates",
    "CHARLOTTE HARUMEG": "🍰 Big Mom Pirates",
    "CHARLOTTE FUYUMEG": "🍰 Big Mom Pirates",
    "CHARLOTTE PUDDING": "🍰 Big Mom Pirates",
    "CHARLOTTE FLAMPE": "🍰 Big Mom Pirates",
    "CHARLOTTE WAFERS": "🍰 Big Mom Pirates",
    "CHARLOTTE NORMANDE": "🍰 Big Mom Pirates",
    "CHARLOTTE ANANA": "🍰 Big Mom Pirates",
    "NITRO": "🌍 Other",
    "RABIAN": "🌍 Other",
    "NAPOLEON": "🌍 Other",
    "PROMETHEUS": "🌍 Other",
    "ZEUS": "🌍 Other",
    "SEA ANTS": "🌍 Other",
    "ARISTOCROC": "🌍 Other",
    "POUND": "🌍 Other",
    "RANDOLPH": "🌍 Other",
    "CAPONE PEZ": "🌍 Other",
    "KINGBAUM": "🌍 Other",
    "COSETTE": "🌍 Other",
    "EPONY": "🌍 Other",
    "UNICORN": "🌍 Other",
    "KINOKOBITO": "🌍 Other",
    "DOSKOI PANDA": "🌍 Other",
    "CHESS PEACEKEEPERS": "🌍 Other",
    "DIESEL": "🌍 Other",
    "EGGPLANT SOLDIER": "🌍 Other",
    "ZEPO": "🌍 Other",
    "BOBBIN": "🌍 Other",
    "STREUSEN": "🌍 Other",
    "STUSSY": "🌍 Other",
    "DU FELD": "🌍 Other",
    "MORGANS": "🌍 Other",
    "DRUG PECLO": "🌍 Other",
    "GIBERSON": "🌍 Other",
    "UMIT": "🌍 Other",
    "JIGRA": "🌍 Other",
    "CARMEL (MOTHER)": "🌍 Other",
    "GERD": "🌍 Other",
    "RAIDEEN": "🌍 Other",
    "JORUL": "🌍 Other",
    "JARUL": "🌍 Other",
    "PANDORA": "🌍 Other",
    "LADY TREE": "🌍 Other",
    "TART TANKS": "🌍 Other",
    "OOKLICIA": "🌍 Other",
    "CHICHILISIA": "🌍 Other",
    "WCI 31": "🌍 Other",
    "BOUCHE": "🌍 Other",
    "COMANE": "🌍 Other",
    "PEACHBEARD": "🌍 Other",
    "MORLEY": "🌍 Other",
    "BELO BETTY": "🌍 Other",
    "LINDBERGH": "🌍 Other",
    "KARASU": "🌍 Other",
    "BEER VI": "🌍 Other",
    "MATRYOSHESSES": "🌍 Other",
    "HAM BURGER": "🌍 Other",
    "MOROLLON": "🌍 Other",
    "TACO": "🌍 Other",
    "AHIRU": "🌍 Other",
    "TOKIKAKE (CHATON)": "🌍 Other",
    "GION (MOMOUSAGI)": "🌍 Other",
    "SLAVE #3": "🌍 Other",
    "SEKI": "🌍 Other",
    "TAMA (SPHINX)": "🌍 Other",
    "RODO": "🌍 Other",
    "GOLDBERG": "🌍 Other",
    "COLUMBUS": "🌍 Other",
    "KOZUKI ODEN": "🌍 Other",
    "KOZUKI TOKI": "🌍 Other",
    "KOZUKI HIYORI (KOMURASAKI)": "🌍 Other",
    "DENJIRO (KYOSHIRO)": "🌍 Other",
    "KIKUNOJO (OKIKU)": "🌍 Other",
    "ASHURA DOJI (SHUTENMARU)": "🌍 Other",
    "KAWAMATSU": "🌍 Other",
    "SHINOBU": "🌍 Other",
    "MINATOMO": "🌍 Other",
    "TOAD BOINGNOSUKE": "🌍 Other",
    "KOMACHIYO": "🌍 Other",
    "HIHIMARU": "🌍 Other",
    "OTAMA": "🌍 Other",
    "BUNBUKU": "🌍 Other",
    "TENGUYAMA HITETSU": "🌍 Other",
    "DUCKY BREE": "🌍 Other",
    "MIHAL": "🌍 Other",
    "AGGIE 68": "🌍 Other",
    "SHARKODILE": "🌍 Other",
    "KOMA DEER": "🌍 Other",
    "OTSURU": "⚓ Marines",
    "URASHIMA": "🌍 Other",
    "BAT-MAN": "🌍 Other",
    "GAZELLE-MAN": "🌍 Other",
    "MOUSE-MAN": "🌍 Other",
    "HOLDEM": "🌍 Other",
    "KAMIJIRO": "🌍 Other",
    "SMART SNAILS": "🌍 Other",
    "SPEED": "🌍 Other",
    "SARAHEBI": "🌍 Other",
    "JIBUEMON": "🌍 Other",
    "GOROBE": "🌍 Other",
    "KING": "🌍 Other",
    "QUEEN": "🌍 Other",
    "WADO ICHIMONJI (SWORD)": "🌍 Other",
    "KITETSU III (SWORD)": "🌍 Other",
    "SHUSUI (SWORD)": "🌍 Other",
    "HYOGORO (OLD MAN HYO)": "🌍 Other",
    "DOBON": "🌍 Other",
    "KUNI": "🌍 Other",
    "KAKU": "🌍 Other",
    "SUKE": "🌍 Other",
    "TOKO": "🌍 Other",
    "BINGOH": "🌍 Other",
    "BUNGOH": "🌍 Other",
    "BONGOH": "🌍 Other",
    "PAWN SHOP OWNER": "🌍 Other",
    "KUMAGORO": "🌍 Other",
    "KOBEI": "🌍 Other",
    "KISEGAWA": "🌍 Other",
    "TOKIJIRO": "🌍 Other",
    "RAKUDA": "🌍 Other",
    "SHIMOTSUKI YASUIE (TONOYASU)": "🌍 Other",
    "KUROZUMI OROCHI": "🌍 Other",
    "PAGE ONE": "🌍 Other",
    "FUKUROKUJU": "🌍 Other",
    "DAIKOKU": "🌍 Other",
    "HANZO": "🌍 Other",
    "SARUTOBI": "🌍 Other",
    "KAZEKAGE": "🌍 Other",
    "JIGOKU-BENTEN": "🌍 Other",
    "FUJIN": "🌍 Other",
    "RAIJIN": "🌍 Other",
    "BISHAMON": "🌍 Other",
    "CHOME": "🌍 Other",
    "YAZAEMON": "🌍 Other",
    "ALPACA-MAN": "🌍 Other",
    "DAIFUGO": "🌍 Other",
    "SOLITAIRE": "🌍 Other",
    "BABANUKI": "🌍 Other",
    "SANSUKE OCTOPUS": "🌍 Other",
    "GYUKIMARU (ONIMARU)": "🌍 Other",
    "MADILLO-MAN": "🌍 Other",
    "BEAN-WASHING HAG": "🌍 Other",
    "KOMA DANE": "🌍 Other",
    "KOMA BIRD": "🌍 Other",
    "NAY MINGHEIM": "🌍 Other",
    "HOTEI": "🌍 Other",
    "OHMASA": "🌍 Other",
    "TSUNAGORO": "🌍 Other",
    "OCHO": "🌍 Other",
    "YATAPPE": "🌍 Other",
    "SHIMOTSUKI USHIMARU": "🌍 Other",
    "ROCKS D.  XEBEC": "🌍 Other",
    "BLACK BLADE NIGHT LADY (SWORD)": "🌍 Other",
    "EXTRA GIRL (SWORD)": "🌍 Other",
    "KOZUKI SUKIYAKI": "🌍 Other",
    "KOYAMA (BOAR)": "🌍 Other",
    "YAMA (BOAR)": "🌍 Other",
    "KUROZUMI SEMIMARU": "🌍 Other",
    "KUROZUMI HIGURASHI": "🌍 Other",
    "SCOPPER GABAN": "🌍 Other",
    "SEAGULL GANZ NOZUDON": "🌍 Other",
    "SAMBEL": "🌍 Other",
    "MILLE PINE": "🌍 Other",
    "GANRYU": "🌍 Other",
    "DORINGO": "🌍 Other",
    "TARO": "🌍 Other",
    "PEETAMU": "🌍 Other",
    "DONKINO": "🌍 Other",
    "CB GALLANT": "🌍 Other",
    "YUEY": "🌍 Other",
    "MOON ISAAC Jr. ": "🌍 Other",
    "MAX MARX": "🌍 Other",
    "SPENCER": "🌍 Other",
    "Mr.  MOMORA": "🌍 Other",
    "LOWWING": "🌍 Other",
    "ELIO": "🌍 Other",
    "BANCRO": "🌍 Other",
    "JACKSON BURNER": "🌍 Other",
    "GENGHIS BAAN": "🌍 Other",
    "ULTI": "🌍 Other",
    "WHO'S-WHO": "🌍 Other",
    "BLACK MARIA": "🌍 Other",
    "SASAKI": "🌍 Other",
    "STRAW HAT (HUMAN FORM)": "🌍 Other",
    "BAO HUANG": "🌍 Other",
    "HACCHA": "🌍 Other",
    "YAMATO": "🌍 Other",
}

def get_crew(name):
    return CREWS.get(name,'🌍 Other')
