name: Deploy to Server

on:
  push:
    branches:
      - main # Change this to 'master' if your default branch is master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SERVER_SSH_KEY }}
        known_hosts: 'placeholder'

    # Step 3: Add the server to known hosts using port 2022
    - name: Adding Known Hosts
      run: ssh-keyscan -p 2022 -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    # Step 4: Deploy with rsync using port 2022
    # Be sure to change the very end to match your specific server folder!
    - name: Deploy with rsync
      run: |
        rsync -avz -e "ssh -p 2022" --delete ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/container/
